version: "3.8"

services:
  backend:
    build: .
    container_name: backend-api
    depends_on:
      - db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin_123"
      POSTGRES_DB: "sistemabl"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin_123"
      POSTGRES_DB: "sistemabl"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
